language: node_js
sudo: false
before_script:
  - npm link
  - npm link kefir
node_js:
  - 6
  - 8
  - stable
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6649afda84024922a25d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
