language: node_js
sudo: false
node_js:
- '4'
- '7'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6649afda84024922a25d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
